title: John-Paul Dickie

author: John-Paul Dickie

permalink: /blog/:title/
lang: en_GB

show_excerpts: true
excerpt_separator: <!--more-->

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate-v2


# Pagination Settings
pagination:
  enabled: true
  per_page: 8
  permalink: '/blog/page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

twitter_username: johnpauldickie
title_image: /assets/img/jp.png
