title: John-Paul Dickie

author: John-Paul Dickie

permalink: /blog/:title/
lang: en_GB

show_excerpts: true
excerpt_separator: <!--more-->

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

twitter_username: johnpauldickie
