title: John-Paul Dickie
url: https://www.johnpauldickie.co.uk
author: John-Paul Dickie
description: "Hi, I'm John-Paul, a user-centred content designer, making content simple, clear and concise."

permalink: /blog/:title/
lang: en_GB

show_excerpts: true
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-tfidf-related-posts

# Pagination Settings
pagination:
  enabled: true
  per_page: 8
  permalink: '/blog/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

twitter_username: johnpauldickie
title_image: /assets/img/jp.png

related_posts_count: 2

include:
  - _redirects
