title: John-Paul Dickie
url: https://www.johnpauldickie.co.uk
author: John-Paul Dickie
description: Content designer working at the Government Digital Service.

permalink: /blog/:title/
lang: en_GB

show_excerpts: true
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate-v2


# Pagination Settings
pagination:
  enabled: true
  per_page: 8
  permalink: '/blog/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

twitter_username: johnpauldickie
title_image: /assets/img/jp.png
